apiVersion: v1
kind: Namespace
metadata:
  name: symfony-microservice
---
apiVersion: v1
kind: Service
metadata:
  namespace: symfony-microservice
  name: symfony-service
spec:
  selector:
    app: symfony
  type: ClusterIP  # Change to ClusterIP
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: symfony-microservice
  name: symfony-deployment
  labels:
    app: symfony
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symfony
  template:
    metadata:
      labels:
        app: symfony
    spec:
      containers:
        - name: symfony
          image: ivanaki/symfony-microservice
          ports:
            - containerPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: symfony-microservice-ingress
  namespace: symfony-microservice
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /micro
        pathType: Prefix
        backend:
          service:
            name: symfony-service
            port:
              number: 8087
